nodered:
  build: .
  ports:
    - "1880:1880"
  environment:
    - FLOWS=/myData/my_flows.json
  links:
    - influxdb
  volumes:
    - /mnt/stateful_partition/home/xavier_moulin_soprasteria/btnconnecte/myData:/myData

influxdb:
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root
    - PRE_CREATE_DB=indicateurs
  volumes:
    - /mnt/stateful_partition/home/xavier_moulin_soprasteria/btnconnecte/myData:/myData

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
  volumes:
    - /mnt/stateful_partition/home/xavier_moulin_soprasteria/btnconnecte/myData:/myData
